Don't be verbose in the triggerDeploy. It's noisy and has what are probably benign k8s versioning errors
com.openshift.restclient.OpenShiftException: Exception trying to PUT https://172.30.0.1/api/v1/namespaces/test-project/replicationcontrollers/leprechaun-jenkins-blue-test-40 response code: 409 Operation cannot be fulfilled on replicationcontrollers "leprechaun-jenkins-blue-test-40": the object has been modified; please apply your changes to the latest version and try again
	at com.openshift.internal.restclient.okhttp.ResponseCodeInterceptor.createOpenShiftException(ResponseCodeInterceptor.java:114)
	at com.openshift.internal.restclient.okhttp.ResponseCodeInterceptor.intercept(ResponseCodeInterceptor.java:65)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)
	at okhttp3.RealCall.execute(RealCall.java:60)
	at com.openshift.internal.restclient.DefaultClient.execute(DefaultClient.java:258)
	at com.openshift.internal.restclient.DefaultClient.execute(DefaultClient.java:222)
	at com.openshift.internal.restclient.DefaultClient.execute(DefaultClient.java:210)
	at com.openshift.internal.restclient.DefaultClient.update(DefaultClient.java:316)
	at com.openshift.jenkins.plugins.pipeline.model.RetryIClient.lambda$update$11(RetryIClient.java:205)
	at com.openshift.jenkins.plugins.pipeline.model.RetryIClient.retry(RetryIClient.java:72)
	at com.openshift.jenkins.plugins.pipeline.model.RetryIClient.update(RetryIClient.java:205)
	at com.openshift.jenkins.plugins.pipeline.model.IOpenShiftPlugin.annotateJobInfoToResource(IOpenShiftPlugin.java:630)
	at com.openshift.jenkins.plugins.pipeline.model.IOpenShiftDeployer.coreLogic(IOpenShiftDeployer.java:85)
	at com.openshift.jenkins.plugins.pipeline.model.IOpenShiftPlugin.doItCore(IOpenShiftPlugin.java:309)
	at com.openshift.jenkins.plugins.pipeline.dsl.OpenShiftDeployerExecution.run(OpenShiftDeployerExecution.java:42)
	at com.openshift.jenkins.plugins.pipeline.dsl.OpenShiftDeployerExecution.run(OpenShiftDeployerExecution.java:18)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1$1.call(AbstractSynchronousNonBlockingStepExecution.java:47)
	at hudson.security.ACL.impersonate(ACL.java:260)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
com.openshift.restclient.OpenShiftException: Exception trying to PUT https://172.30.0.1/api/v1/namespaces/test-project/replicationcontrollers/leprechaun-jenkins-blue-test-40 response code: 409 Operation cannot be fulfilled on replicationcontrollers "leprechaun-jenkins-blue-test-40": the object has been modified; please apply your changes to the latest version and try again
	at com.openshift.internal.restclient.okhttp.ResponseCodeInterceptor.createOpenShiftException(ResponseCodeInterceptor.java:114)
	at com.openshift.internal.restclient.okhttp.ResponseCodeInterceptor.intercept(ResponseCodeInterceptor.java:65)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)
	at okhttp3.RealCall.execute(RealCall.java:60)
	at com.openshift.internal.restclient.DefaultClient.execute(DefaultClient.java:258)
	at com.openshift.internal.restclient.DefaultClient.execute(DefaultClient.java:222)
	at com.openshift.internal.restclient.DefaultClient.execute(DefaultClient.java:210)
	at com.openshift.internal.restclient.DefaultClient.update(DefaultClient.java:316)
	at com.openshift.jenkins.plugins.pipeline.model.RetryIClient.lambda$update$11(RetryIClient.java:205)
	at com.openshift.jenkins.plugins.pipeline.model.RetryIClient.retry(RetryIClient.java:72)
	at com.openshift.jenkins.plugins.pipeline.model.RetryIClient.update(RetryIClient.java:205)
	at com.openshift.jenkins.plugins.pipeline.model.IOpenShiftPlugin.annotateJobInfoToResource(IOpenShiftPlugin.java:630)
	at com.openshift.jenkins.plugins.pipeline.model.IOpenShiftDeployer.coreLogic(IOpenShiftDeployer.java:85)
	at com.openshift.jenkins.plugins.pipeline.model.IOpenShiftPlugin.doItCore(IOpenShiftPlugin.java:309)
	at com.openshift.jenkins.plugins.pipeline.dsl.OpenShiftDeployerExecution.run(OpenShiftDeployerExecution.java:42)
	at com.openshift.jenkins.plugins.pipeline.dsl.OpenShiftDeployerExecution.run(OpenShiftDeployerExecution.java:18)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1$1.call(AbstractSynchronousNonBlockingStepExecution.java:47)
	at hudson.security.ACL.impersonate(ACL.java:260)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
com.openshift.restclient.OpenShiftException: Exception trying to PUT https://172.30.0.1/api/v1/namespaces/test-project/replicationcontrollers/leprechaun-jenkins-blue-test-40 response code: 409 Operation cannot be fulfilled on replicationcontrollers "leprechaun-jenkins-blue-test-40": the object has been modified; please apply your changes to the latest version and try again
	at com.openshift.internal.restclient.okhttp.ResponseCodeInterceptor.createOpenShiftException(ResponseCodeInterceptor.java:114)
	at com.openshift.internal.restclient.okhttp.ResponseCodeInterceptor.intercept(ResponseCodeInterceptor.java:65)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)
	at okhttp3.RealCall.execute(RealCall.java:60)
	at com.openshift.internal.restclient.DefaultClient.execute(DefaultClient.java:258)
	at com.openshift.internal.restclient.DefaultClient.execute(DefaultClient.java:222)
	at com.openshift.internal.restclient.DefaultClient.execute(DefaultClient.java:210)
	at com.openshift.internal.restclient.DefaultClient.update(DefaultClient.java:316)
	at com.openshift.jenkins.plugins.pipeline.model.RetryIClient.lambda$update$11(RetryIClient.java:205)
	at com.openshift.jenkins.plugins.pipeline.model.RetryIClient.retry(RetryIClient.java:72)
	at com.openshift.jenkins.plugins.pipeline.model.RetryIClient.update(RetryIClient.java:205)
	at com.openshift.jenkins.plugins.pipeline.model.IOpenShiftPlugin.annotateJobInfoToResource(IOpenShiftPlugin.java:630)
	at com.openshift.jenkins.plugins.pipeline.model.IOpenShiftDeployer.coreLogic(IOpenShiftDeployer.java:85)
	at com.openshift.jenkins.plugins.pipeline.model.IOpenShiftPlugin.doItCore(IOpenShiftPlugin.java:309)
	at com.openshift.jenkins.plugins.pipeline.dsl.OpenShiftDeployerExecution.run(OpenShiftDeployerExecution.java:42)
	at com.openshift.jenkins.plugins.pipeline.dsl.OpenShiftDeployerExecution.run(OpenShiftDeployerExecution.java:18)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1$1.call(AbstractSynchronousNonBlockingStepExecution.java:47)
	at hudson.security.ACL.impersonate(ACL.java:260)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
WARNING: Failed to annotate ReplicationController leprechaun-jenkins-blue-test-40 with job information.

OpenShiftDeploy current phase New

OpenShiftDeployer wait 10 seconds, then try oc deploy again
OpenShiftDeployer returned rep ctrl {"kind" : "ReplicationController", "apiVersion" : "v1", "metadata" : {"name" : "leprechaun-jenkins-blue-test-40", "namespace" : "test-project", "selfLink" : "/api/v1/namespaces/test-project/replicationcontrollers/leprechaun-jenkins-blue-test-40", "uid" : "fe1a972c-7b3c-11e7-9a31-ca288df5a19f", "resourceVersion" : "35900", "generation" : 2, "creationTimestamp" : "2017-08-07T06:52:34Z", "labels" : {"app" : "leprechaun-jenkins-blue-test", "openshift.io/deployment-config.name" : "leprechaun-jenkins-blue-test"}, "annotations" : {"openshift.io/deployer-pod.name" : "leprechaun-jenkins-blue-test-40-deploy", "openshift.io/deployment-config.latest-version" : "40", "openshift.io/deployment-config.name" : "leprechaun-jenkins-blue-test", "openshift.io/deployment.phase" : "Complete", "openshift.io/deployment.replicas" : "", "openshift.io/deployment.status-reason" : "manual change", "openshift.io/encoded-deployment-config" : "{\"kind\":\"DeploymentConfig\",\"apiVersion\":\"v1\",\"metadata\":{\"name\":\"leprechaun-jenkins-blue-test\",\"namespace\":\"test-project\",\"selfLink\":\"/oapi/v1/namespaces/test-project/deploymentconfigs/leprechaun-jenkins-blue-test\",\"uid\":\"8d63533a-7a66-11e7-9a31-ca288df5a19f\",\"resourceVersion\":\"35844\",\"generation\":50,\"creationTimestamp\":\"2017-08-06T05:17:33Z\",\"labels\":{\"app\":\"leprechaun-jenkins-blue-test\"},\"annotations\":{\"kubectl.kubernetes.io/last-applied-configuration\":\"{\\\"kind\\\":\\\"DeploymentConfig\\\",\\\"apiVersion\\\":\\\"v1\\\",\\\"metadata\\\":{\\\"name\\\":\\\"leprechaun-jenkins-blue-test\\\",\\\"creationTimestamp\\\":null,\\\"labels\\\":{\\\"app\\\":\\\"leprechaun-jenkins-blue-test\\\"}},\\\"spec\\\":{\\\"strategy\\\":{\\\"type\\\":\\\"Rolling\\\",\\\"rollingParams\\\":{\\\"updatePeriodSeconds\\\":1,\\\"intervalSeconds\\\":1,\\\"timeoutSeconds\\\":600,\\\"maxUnavailable\\\":\\\"25%\\\",\\\"maxSurge\\\":\\\"25%\\\"},\\\"resources\\\":{}},\\\"triggers\\\":null,\\\"replicas\\\":1,\\\"test\\\":false,\\\"selector\\\":{\\\"app\\\":\\\"leprechaun-jenkins-blue-test\\\",\\\"deploymentconfig\\\":\\\"leprechaun-jenkins-blue-test\\\"},\\\"template\\\":{\\\"metadata\\\":{\\\"creationTimestamp\\\":null,\\\"labels\\\":{\\\"app\\\":\\\"leprechaun-jenkins-blue-test\\\",\\\"deploymentconfig\\\":\\\"leprechaun-jenkins-blue-test\\\"}},\\\"spec\\\":{\\\"containers\\\":[{\\\"name\\\":\\\"leprechaun-jenkins-blue-test\\\",\\\"image\\\":\\\"172.30.1.1:5000/test-project/leprechaun-jenkins-blue-test:latest\\\",\\\"ports\\\":[{\\\"containerPort\\\":8080,\\\"protocol\\\":\\\"TCP\\\"}],\\\"resources\\\":{}}],\\\"restartPolicy\\\":\\\"Always\\\",\\\"terminationGracePeriodSeconds\\\":30,\\\"dnsPolicy\\\":\\\"ClusterFirst\\\"}}},\\\"status\\\":{\\\"latestVersion\\\":0,\\\"observedGeneration\\\":0,\\\"replicas\\\":0,\\\"updatedReplicas\\\":0,\\\"availableReplicas\\\":0,\\\"unavailableReplicas\\\":0}}\"}},\"spec\":{\"strategy\":{\"type\":\"Rolling\",\"rollingParams\":{\"updatePeriodSeconds\":1,\"intervalSeconds\":1,\"timeoutSeconds\":600,\"maxUnavailable\":\"25%\",\"maxSurge\":\"25%\"},\"resources\":{},\"activeDeadlineSeconds\":21600},\"triggers\":[{\"type\":\"ConfigChange\"}],\"replicas\":1,\"test\":false,\"selector\":{\"app\":\"leprechaun-jenkins-blue-test\",\"deploymentconfig\":\"leprechaun-jenkins-blue-test\"},\"template\":{\"metadata\":{\"creationTimestamp\":null,\"labels\":{\"app\":\"leprechaun-jenkins-blue-test\",\"deploymentconfig\":\"leprechaun-jenkins-blue-test\"}},\"spec\":{\"containers\":[{\"name\":\"leprechaun-jenkins-blue-test\",\"image\":\"172.30.1.1:5000/test-project/leprechaun-jenkins-blue-test:latest\",\"ports\":[{\"containerPort\":8080,\"protocol\":\"TCP\"}],\"resources\":{},\"terminationMessagePath\":\"/dev/termination-log\",\"imagePullPolicy\":\"Always\"}],\"restartPolicy\":\"Always\",\"terminationGracePeriodSeconds\":30,\"dnsPolicy\":\"ClusterFirst\",\"securityContext\":{}}}},\"status\":{\"latestVersion\":40,\"observedGeneration\":49,\"replicas\":1,\"updatedReplicas\":1,\"availableReplicas\":1,\"unavailableReplicas\":0,\"details\":{\"message\":\"manual change\",\"causes\":[{\"type\":\"Manual\"}]},\"conditions\":[{\"type\":\"Available\",\"status\":\"True\",\"lastUpdateTime\":\"2017-08-07T03:14:31Z\",\"lastTransitionTime\":\"2017-08-07T03:14:31Z\",\"message\":\"Deployment config has minimum availability.\"},{\"type\":\"Progressing\",\"status\":\"True\",\"lastUpdateTime\":\"2017-08-07T06:51:18Z\",\"lastTransitionTime\":\"2017-08-07T06:51:17Z\",\"reason\":\"NewReplicationControllerAvailable\",\"message\":\"replication controller \\\"leprechaun-jenkins-blue-test-39\\\" successfully rolled out\"}],\"readyReplicas\":1}}\n"}}, "spec" : {"replicas" : 1, "selector" : {"app" : "leprechaun-jenkins-blue-test", "deployment" : "leprechaun-jenkins-blue-test-40", "deploymentconfig" : "leprechaun-jenkins-blue-test"}, "template" : {"metadata" : {"labels" : {"app" : "leprechaun-jenkins-blue-test", "deployment" : "leprechaun-jenkins-blue-test-40", "deploymentconfig" : "leprechaun-jenkins-blue-test"}, "annotations" : {"openshift.io/deployment-config.latest-version" : "40", "openshift.io/deployment-config.name" : "leprechaun-jenkins-blue-test", "openshift.io/deployment.name" : "leprechaun-jenkins-blue-test-40"}}, "spec" : {"containers" : [{"name" : "leprechaun-jenkins-blue-test", "image" : "172.30.1.1:5000/test-project/leprechaun-jenkins-blue-test:latest", "ports" : [{"containerPort" : 8080, "protocol" : "TCP"}], "resources" : {}, "terminationMessagePath" : "/dev/termination-log", "imagePullPolicy" : "Always"}], "restartPolicy" : "Always", "terminationGracePeriodSeconds" : 30, "dnsPolicy" : "ClusterFirst", "securityContext" : {}}}}, "status" : {"replicas" : 1, "fullyLabeledReplicas" : 1, "readyReplicas" : 1, "availableReplicas" : 1, "observedGeneration" : 2}}

Exiting "Trigger OpenShift Deployment" successfully; deployment "leprechaun-jenkins-blue-test-40" has completed with status:  [Complete].